name: unique_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.11.0 <4.0.0'

resolution: workspace

dependencies:
  serverpod: 4.1.0-beta.1
  serverpod_auth_idp_server: 4.1.0-beta.1
  serverpod_cloud_storage: 4.1.0-beta.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 4.1.0-beta.1
  test: ^1.25.5

serverpod:
  scripts:
    flutter_build:
      windows: >-
        (if exist web\app rmdir /S /Q web\app)
        & cd /D ..\unique_flutter
        & set ARGS=web --base-href /
        && (call flutter build %ARGS% || (flutter clean && call flutter build %ARGS%))
        && xcopy /E /I /Y build\web ..\unique_server\web\app
      posix: |
        rm -rf ../unique_server/web/app
        cd ../unique_flutter
        set -- web --base-href / --output ../unique_server/web/app
        flutter build "$@" || { flutter clean && flutter build "$@"; }

  flutter_apps:
    unique:
      path: ../unique_flutter
      displayName: "Unique app"
      auto_launch: true
      target: lib/driver.dart
