targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - tools/drift_worker.dart
      - "!build/**"
      - "!**/build/**"
      - "!**/generated/**"
    builders:
      drift_dev:
        options:
          databases:
            default: lib/src/storage/drift/app_database.dart
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules:
                - fts5
      build_web_compilers:entrypoint:
        generate_for:
          - tools/drift_worker.dart
        options:
          compiler: dart2js
      ":copy_compiled_worker_js":
        enabled: true

builders:
  copy_compiled_worker_js:
    import: "tools/builder.dart"
    builder_factories: ["CopyCompiledJs.new"]
    required_inputs:
      - .js
    build_to: source
    build_extensions:
      "tools/drift_worker.dart": ["web/drift_worker.js"]
